package dao;

import org.apache.ibatis.annotations.Param;
import pojo.Guide;

import java.util.List;

public interface GuideMapper {
    public List<Guide> allGuideBScenery_id(@Param("scenery_id") int scenery_id);

    /***************************后台***********************************/
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbggenerated Mon Mar 23 16:37:14 CST 2020
     */
    int deleteByPrimaryKey(Integer guide_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbggenerated Mon Mar 23 16:37:14 CST 2020
     */
    int insert(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbggenerated Mon Mar 23 16:37:14 CST 2020
     */
    int insertSelective(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbggenerated Mon Mar 23 16:37:14 CST 2020
     */
    Guide selectByPrimaryKey(Integer guide_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbggenerated Mon Mar 23 16:37:14 CST 2020
     */
    int updateByPrimaryKeySelective(Guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide
     *
     * @mbggenerated Mon Mar 23 16:37:14 CST 2020
     */
    int updateByPrimaryKey(Guide record);

    int getCount();

    List<Guide> getGuideList(@Param("currentPageNo") Integer currentPageNo, @Param("pageSize") Integer pageSize);

    List<Guide> getGuideListByName(@Param("guide_name") String guide_name);

    //以下两条用于爬虫
    public int htaddGuide(@Param("guide") Guide guide);
    public int htselectByName(@Param("guide_name") String guide_name);
}
