package dao;

import pojo.Hotel_room;

import java.util.List;

public interface Hotel_roomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_room
     *
     * @mbggenerated Fri Jan 08 22:15:00 CST 2021
     */
    int deleteByPrimaryKey(Integer room_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_room
     *
     * @mbggenerated Fri Jan 08 22:15:00 CST 2021
     */
    int insert(Hotel_room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_room
     *
     * @mbggenerated Fri Jan 08 22:15:00 CST 2021
     */
    int insertSelective(Hotel_room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_room
     *
     * @mbggenerated Fri Jan 08 22:15:00 CST 2021
     */
    Hotel_room selectByPrimaryKey(Integer room_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_room
     *
     * @mbggenerated Fri Jan 08 22:15:00 CST 2021
     */
    int updateByPrimaryKeySelective(Hotel_room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_room
     *
     * @mbggenerated Fri Jan 08 22:15:00 CST 2021
     */
    int updateByPrimaryKey(Hotel_room record);
    List<Hotel_room> getHotelRoomList(int hotel_id);
}