package dao;

import org.apache.ibatis.annotations.Param;
import pojo.Rest;

import java.util.List;

public interface RestMapper {
    public List<Rest> getRestAreaTop3(@Param("area_id") int area_id);

    public List<Rest> getRestBArea_id(@Param("area_id") int area_id);

    /***************************后台******************************************/
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest
     *
     * @mbggenerated Tue Mar 24 20:16:19 CST 2020
     */
    int deleteByPrimaryKey(Integer rest_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest
     *
     * @mbggenerated Tue Mar 24 20:16:19 CST 2020
     */
    int insert(Rest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest
     *
     * @mbggenerated Tue Mar 24 20:16:19 CST 2020
     */
    int insertSelective(Rest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest
     *
     * @mbggenerated Tue Mar 24 20:16:19 CST 2020
     */
    Rest selectByPrimaryKey(Integer rest_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest
     *
     * @mbggenerated Tue Mar 24 20:16:19 CST 2020
     */
    int updateByPrimaryKeySelective(Rest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest
     *
     * @mbggenerated Tue Mar 24 20:16:19 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Rest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rest
     *
     * @mbggenerated Tue Mar 24 20:16:19 CST 2020
     */
    int updateByPrimaryKey(Rest record);

    int getCount();

    List<Rest> getRestList(@Param("currentPageNo") Integer currentPageNo, @Param("pageSize") Integer pageSize);

    List<Rest> getRestListByName(@Param("rest_name") String rest_name);


    //以下三条用于爬虫
    public int htaddRest(@Param("rest") Rest rest);

    public int htgetRest_idByName(@Param("rest_name") String rest_name);

    public int htselectByName(@Param("rest_name") String rest_name);
}
