package dao;

import org.apache.ibatis.annotations.Param;
import pojo.Strategy;

import java.util.List;

public interface StrategyMapper {
    public int addStrategy(Strategy strategy);

    public List<Strategy> queryAllStrategy();

    public List<Strategy> queryOnesStrategy(@Param("user_id") int user_id);

    public List<Strategy> getOnesRealease0Strategy(@Param("user_id") int user_id);

    public List<Strategy> getOnesRealease2Strategy(@Param("user_id") int user_id);

    public Strategy getStrategyBid(@Param("strategy_id") int strategy_id);

    public int addClickNum(@Param("strategy_id") int strategy_id);

    public List<Strategy> getTop5Strategy();

    public List<Strategy> getStrategyBDiDianTop5(@Param("recommend") String recommend);

    public List<Strategy> getStrategyBDiDian(@Param("recommend") String recommend);

    public int deleteStrategyBID(@Param("strategy_id") int strategy_id);

    public int updateStrategyBID(Strategy strategy);

    public int updateStrategyBIDNocover(Strategy strategy);


    /***************************后台************************************************/
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbggenerated Wed Mar 25 10:11:16 CST 2020
     */
    int deleteByPrimaryKey(Integer strategy_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbggenerated Wed Mar 25 10:11:16 CST 2020
     */
    int insert(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbggenerated Wed Mar 25 10:11:16 CST 2020
     */
    int insertSelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbggenerated Wed Mar 25 10:11:16 CST 2020
     */
    Strategy selectByPrimaryKey(Integer strategy_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbggenerated Wed Mar 25 10:11:16 CST 2020
     */
    int updateByPrimaryKeySelective(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbggenerated Wed Mar 25 10:11:16 CST 2020
     */
    int updateByPrimaryKey(Strategy record);


    int getCount();

    int getUncheckedCount();

    int getUnPassedCount();

    //    未审核名单
    List<Strategy> getUnreviewedList(@Param("currentPageNo") Integer currentPageNo, @Param("pageSize") Integer pageSize);

    //审核通过名单
    List<Strategy> getReviewedList(@Param("currentPageNo") Integer currentPageNo, @Param("pageSize") Integer pageSize);

    List<Strategy> getUnPassedList(@Param("currentPageNo") Integer currentPageNo, @Param("pageSize") Integer pageSize);


}
