package dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import pojo.User;

public interface UserMapper {
    public int addUser(@Param("user_account") String user_account, @Param("user_password") String user_password, @Param("gender") String gender);

    public User getUser(@Param("user_account") String user_account, @Param("user_password") String user_password);

    public User getUserByID(@Param("user_id") int user_id);

    public User getUserByAccount(@Param("user_account") String user_account);

    public int updateUser(@Param("user_id") int user_id, @Param("user_account") String user_account, @Param("user_password") String user_password, @Param("gender") String gender, @Param("head") String head, @Param("intro") String intro);

    public int updateUserNoHead(@Param("user_id") int user_id, @Param("user_account") String user_account, @Param("user_password") String user_password, @Param("gender") String gender, @Param("intro") String intro);

    public int destoryUser(@Param("user_id") int user_id);

    /******************************后台******************************************************************************************/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Mar 20 17:15:50 CST 2020
     */
    int deleteByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Mar 20 17:15:50 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Mar 20 17:15:50 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Mar 20 17:15:50 CST 2020
     */
    User selectByPrimaryKey(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Mar 20 17:15:50 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Fri Mar 20 17:15:50 CST 2020
     */
    int updateByPrimaryKey(User record);

    int getCount();

    List<User> getUserList(@Param("currentPageNo") Integer currentPageNo, @Param("pageSize") Integer pageSize);

    List<User> getUserListByName(@Param("user_account") String user_account);

}
